#!/usr/bin/env sh

interface="en0"

if [ $# -eq 0 ]
then
    echo "Usage: ./monitor-network -i <interface> [-w <file>|-r <file>]";
    exit 1;
fi
    

while [ $# -gt 0 ]; do
    case $1
    in
	-i) interface=$2; shift; shift;;
	-r) read_file=$2; shift; shift;;
	-w) write_file=$2; shift; shift;;
	-v) filter="-v f='0|1|2|3|6'"; shift;;
	-vv) filter="-v show_all=1"; shift;;
	-f) filter="-v f=$2|"; shift; shift;;
	-X) hex="-v hexdump=1"; shift;;
    esac
done

if [ "$read_file" != "" ] && [ "$write_file" != "" ]; then
    echo "Cannot write file and read at the same time.";
    exit 1;
fi

if [ "$read_file" != "" ]; then
    options="-r $read_file";
elif [ "$write_file" != "" ]; then
    options="-w $write_file";
fi

tcpdump -i $interface udp port 2048 -n -l -vv -X $options | gawk -f monitor-network.awk $hex $filter;
