#!/bin/bash

subnet="129.241.187";
remote_dir="/var/tmp/group79";
repo="https://github.com/larskr/elevator-project.git";
branch="master";

if [ $# -eq 0 ]; then
    echo "Usage: ./setup [-d] <list of last byte of the IPs>";
    exit;
fi

dflag='';
while getopts 'd' flag; do
    case "${flag}" in
	d) dflag='true' ;;
	*) exit ;;
    esac
    shift;
done

for ip in $@; do
    ping -c 1 -W 1 "${subnet}.${ip}" > /dev/null
    
    if [[ $? -eq 0 ]]; then

	# Install public ssh key on remote.
	if [[ -r "${HOME}/.ssh/id_rsa.pub" ]]; then
	    cat "${HOME}/.ssh/id_rsa.pub" \
		| ssh "${subnet}.${ip}" 'mkdir -p .ssh; cat >> .ssh/authorized_keys';
	    if [ $? -eq 0 ]; then
		echo "${subnet}.${ip} authorized";
	    fi
	fi
	
	if [[ "${dflag}" = "true" ]]; then
	    if (ssh "${subnet}.${ip}" "[[ -d ${remote_dir} ]]"); then
		ssh "${subnet}.${ip}" \
		    "echo Deleting ${remote_dir} on ${subnet}.${ip}; rm -rI ${remote_dir};";
	    fi
	    continue;
	fi
	
	if (ssh "${subnet}.${ip}" "[[ ! -d ${remote_dir} ]]"); then
	    gnome-terminal -t "${subnet}.${ip}" -x ssh -t "${subnet}.${ip}" \
			"export GOPATH=${remote_dir};"\
			"mkdir -p ${remote_dir};"\
			"cd ${remote_dir};"\
			"mkdir 'src' 'bin' 'pkg';"\
			"cd src;"\
			"git clone ${repo};"\
			"cd elevator-project;"\
			"git checkout ${branch};"\
			"go build -o elevator;"\
			"clear;"\
			"./elevator;"
	else
	    gnome-terminal -t "${subnet}.${ip}" -x ssh -t "${subnet}.${ip}" \
			"export GOPATH=${remote_dir};"\
			"cd ${remote_dir}/src/elevator-project;"\
			"git fetch origin ${branch};"\
			"git reset --hard origin/${branch};"\
			"go build -o elevator;"\
			"clear;"\
			"./elevator;"
	fi
    else
	echo "${subnet}.${ip} not responding";
    fi
done
